name: "Radicati Media"
description: "Sets up base config for media in a Radicati project"
type: "Media"
install:
  - decorative_image_widget
  - dropzonejs
  - dropzonejs_eb_widget
  - file
  - focal_point
  - image
  - imageapi_optimize
  - imageapi_optimize_tinypng
  - link
  - media
  - media_bulk_upload
  - media_bulk_upload_dropzonejs
  - media_entity_download
  - media_library
  - media_library_edit
  - paragraphs
  - responsive_image
config:
  import:
    decorative_image_widget: "*"
    dropzonejs: "*"
    file: "*"
    focal_point: "*"
    image: "*"
    imageapi_optimize: "*"
    imageapi_optimize_tinypng: "*"
    link: "*"
    media: "*"
    media_library: "*"
    media_library_edit: "*"
    paragraphs: "*"
    responsive_image: "*"
